-
  name:  'FrontendAFXConnector show'
  uriPattern: 'afxConnector/show'
  defaults:
    '@package':    'Mireo.FrontendAFXConnector'
    '@controller': 'AfxConnector'
    '@action':     'show'
    '@format':     'html'
  httpMethods: ['POST']

-
  name:  'FrontendAFXConnector save'
  uriPattern: 'afxConnector/save'
  defaults:
    '@package':    'Mireo.FrontendAFXConnector'
    '@controller': 'AfxConnector'
    '@action':     'save'
    '@format':     'json'
  httpMethods: ['POST']

- name:  'FrontendAFXConnector download'
  uriPattern: 'afxConnector/download'
  defaults:
    '@package':    'Mireo.FrontendAFXConnector'
    '@controller': 'AfxConnector'
    '@action':     'download'
    '@format':     'json'
  httpMethods: ['POST']
#  routeParts:
#    'node':
#      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
#  subRoutes:
#    'FrontendSubRoutes':
#      package: 'Neos.Neos'
#      suffix:  'Frontend'
#      variables:
#        'defaultUriSuffix': '<defaultUriSuffix>'
